# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('roll_no', models.CharField(max_length=12)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('semester', models.IntegerField()),
            ],
        ),
    ]
