# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(default='Software Enginneering', max_length=80),
            preserve_default=False,
        ),
    ]
