# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('student', '0002_student_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrolment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='subject.Course')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='student',
            name='contact_number',
            field=models.BigIntegerField(default=8287433970),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='stream',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subject.Stream'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrolment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student'),
        ),
    ]
