# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_stream'),
        ('student', '0004_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrolment',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='enrolment',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='subject.Course'),
        ),
        migrations.AddField(
            model_name='student',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Enrolment',
        ),
    ]
