# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20171105_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='locked',
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
