# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20171105_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='2K14/SE/034', max_length=12),
            preserve_default=False,
        ),
    ]
