# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20171105_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
