# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Re-register', 'Re-register')], max_length=20),
        ),
    ]
