# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_auto_20171105_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.CharField(default='Dr. Ruchika Malhotra', max_length=80),
            preserve_default=False,
        ),
    ]
